#!/bin/bash
#---------------------------------------------------------------------
# File information

# Name          : rxtool
# Purpose       : Simplify compiling and testing workflow
# License       : BSD3 
# Revision      : 0.1.220107
# Author        : smk (sudhanshumohan781@gmail.com)

#---------------------------------------------------------------------
# Control Parameters 

gnss_src_path=$HOME/prefix-3.8/gnss-sdr/src/algorithms/PVT/
gnss_build_path=$HOME/gnss-sdr/build/
#config_file_name=with_our_recorded_data_usrp2932.conf
config_file_name=sampletest.conf
config_file=$HOME/work/$config_file_name
echo $config_file

#---------------------------------------------------------------------
# Optional Compile Flag processing 
if [[ $1 == "--makesdr" ]]
then
    echo "Starting compilation..."
    pushd $gnss_build_path
    cmake ..
    make
    popd
    ln -sf $HOME/gnss-sdr/install/gnss-sdr $HOME/bin/
    echo "Ending compilation..."
    exit 0
fi
if [[ $1 == "--makegps" ]]
then
# GPS-SDR-SIM
    pushd $HOME/gps-sdr-sim
    gcc gpssim.c -lm -O3 -o gps-sdr-sim
    ln -sf $HOME/gps-sdr-sim/gps-sdr-sim $HOME/bin/
    popd
    exit 0
fi

#---------------------------------------------------------------------
# Running GNSS-SDR

echo "Starting first run..."
mkdir -p $HOME/tmp/
pushd $HOME/tmp/
# cleanup previous run
rm -rf *
# copies cofig to tmp folder for run
cp $config_file .

pushd $HOME/prefix-3.8/
. setup_env.sh
/home/gnss-pc1/prefix-3.8/bin/gnss-sdr -c $config_file_name
popd

echo "Printing Rinex File ... "
# wait for rinex file to appear
sleep 2
if [[ ! -f `find . -name "*\.??N"` ]]
then
    echo "Couldn't locate Rinex File."
    echo "Exiting, Please try running rxtool again."
    exit 0
fi
# Prints recorded rinex file
cat < `find . -name "*\.??N"`
#---------------------------------------------------------------------
# Running GPS-SDR-SIM with the rinex just produced
# currently its sequential but it should be done parallely
gps-sdr-sim -e `find . -name "*\.??N"` -s 4000000 -d 100

# then run on gpssim.bin
popd

echo "Ending Run."
#---------------------------------------------------------------------
# EOF
