#!/bin/bash

#---------------------------------------------------------------------
# Control Parameters
GPS_SDR_BIN=$HOME/bin/gps-sdr-sim
PY_UHD_TRANSMITTER=$HOME/gps-sdr-sim/gps-sdr-sim-uhd.py
UHD_TRANSMITTER=$HOME/prefix4.0/lib/uhd/examples/tx_samples_from_file
EPHEMERIS_FILE=$HOME/tmp/gps_ephemeris.xml
GPSSIM_BIN_CREATE=$HOME/tmp/gpsspoofing.bin
#GPSSIM_BIN_BROADCAST=$HOME/tmp/gpsspoofing.bin
GPSSIM_BIN_BROADCAST=$HOME/gps-sdr-sim/gpssim.bin
freq=2500000
sim_duration=100
broadcast_addr=192.168.13.5
broadcast_program=1                             # TYPE = 0 or 1
gain=0
date=$(date '+%Y/%m/%d,%H:%M:%S')

#---------------------------------------------------------------------
# Sequence Worker Actions
pushd $HOME/prefix4.0/
. setup_env.sh
popd

#---------------------------------------------------------------------
# ERROR Checking
# Make a bash function here to clean up things 
if [[ -f $GPS_SDR_SIM ]]
then
    echo "[ERROR]: NO gps-sdr-sim file found !"
    exit 127
fi
#if [[ -f $PY_UHD_TRANSMITTER ]]
#then
#    echo "[ERROR]: NO gps-sdr-sim-uhd.py file found !"
#    exit 127
#fi
#if [[ -f $UHD_TRANSMITTER ]]
#then
#    echo "[ERROR]: NO tx_samples_from_file file found !"
#    exit 127
#fi

if [[ $GPS_BIN_CREATE -ne $GPS_BIN_BROADCAST ]]
then
    echo "[WARNING]: You are not broadcasting the created binary file!"
fi


#----------------------- BINARY GENERATION ---------------------------
#$GPS_SDR_BIN -e $EPHEMERIS_FILE -d $sim_duration -t $date \
#        -l "30.286,120.141,100" -o $GPSSIM_BIN_CREATE -s $freq

#--------------------------- TRANSMITTER -----------------------------
if [[ $broadcast_program -eq 0 ]]
then
$UHD_TRANSMITTER --args="type=usrp2,addr=$broadcast_addr" \
        --file $GPSSIM_BIN_BROADCAST --type short --rate $freq \
        --freq 1575420000 --gain $gain --repeat NULL

elif [[ $broadcast_program -eq 1 ]]
then
python3 $PY_UHD_TRANSMITTER -t $GPSSIM_BIN_BROADCAST -s $freq -x $gain \
        --args=type="usrp2,addr=$broadcast_addr"
else
    echo "Invalid Transmitter Program Selected !"
fi
#---------------------------------------------------------------------
exit 0
# EOF 
