#!/bin/bash

#---------------------------------------------------------------------
# Control Parameters
GPS_SDR_BIN=$HOME/bin/gps-sdr-sim
TX_SAMPLES_FROM_FILE=$HOME/prefix4.0/lib/uhd/examples/tx_samples_from_file
EPHEMERIS_FILE=$HOME/tmp/gps_ephemeris.xml
GPSSIM_BIN_CREATE=$HOME/tmp/gpssim.bin
GPSSIM_BIN_BROADCAST=$HOME/tmp/gpssim.bin
GPS_SDR_SIM_UHD=$HOME/gps-sdr-sim/gps-sdr-sim-uhd.py
freq=4000000
sim_duration=100
addr=192.168.13.5
gain=0

#---------------------------------------------------------------------
# Sequence Worker Actions
pushd $HOME/prefix4.0/
. setup_env.sh
popd

#----------------------- BINARY GENERATION ---------------------------
$GPS_SDR_BIN -e $EPHEMERIS_FILE -d $sim_duration \
        -l "30.286,120.141,100" -o $GPSSIM_BIN_CREATE -s $freq

#--------------------------- TRANSMITTER -----------------------------
# $TX_SAMPLES_FROM_FILE --args="type=usrp2,addr=$freq" \
#        --file $GPSSIM_BIN_BROADCAST --type short --rate 2600000 \
#        --freq 1575420000 --gain 30 --repeat NULL
python3 $GPS_SDR_SIM_UHD -t $GPSSIM_BIN_BROADCAST -s $freq -x $gain \
        --args=type="usrp2,addr=$addr"
#---------------------------------------------------------------------
# EOF 
